<?php

use Illuminate\Database\Seeder;
use App\Model\WeeklyDishList;

class WeeklyDishListsTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $data = [
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 1],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 2],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 3],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 4],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 5],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 6],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 7],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 8],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 9],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 10],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 11],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 12],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 13],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 14],
            ['day' => 'Monday', 'order_type_id' => 2, 'dish_id' => 15],
            ['day' => 'Tuesday', 'order_type_id' => 2, 'dish_id' => 1],
            ['day' => 'Tuesday', 'order_type_id' => 2, 'dish_id' => 2],
            ['day' => 'Tuesday', 'order_type_id' => 2, 'dish_id' => 3],
            ['day' => 'Tuesday', 'order_type_id' => 2, 'dish_id' => 4],
            ['day' => 'Tuesday', 'order_type_id' => 2, 'dish_id' => 5],
            ['day' => 'Tuesday', 'order_type_id' => 2, 'dish_id' => 6],
            ['day' => 'Tuesday', 'order_type_id' => 2, 'dish_id' => 7],
            ['day' => 'Wednesday', 'order_type_id' => 2, 'dish_id' => 3],
            ['day' => 'Wednesday', 'order_type_id' => 2, 'dish_id' => 4],
            ['day' => 'Wednesday', 'order_type_id' => 2, 'dish_id' => 5],
            ['day' => 'Wednesday', 'order_type_id' => 2, 'dish_id' => 6],
            ['day' => 'Wednesday', 'order_type_id' => 2, 'dish_id' => 7],
            ['day' => 'Wednesday', 'order_type_id' => 2, 'dish_id' => 8],
            ['day' => 'Wednesday', 'order_type_id' => 2, 'dish_id' => 9],
            ['day' => 'Wednesday', 'order_type_id' => 2, 'dish_id' => 10],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 1],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 2],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 5],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 6],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 7],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 8],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 9],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 14],
            ['day' => 'Thursday', 'order_type_id' => 2, 'dish_id' => 15],
            ['day' => 'Friday', 'order_type_id' => 2, 'dish_id' => 1],
            ['day' => 'Friday', 'order_type_id' => 2, 'dish_id' => 2],
            ['day' => 'Friday', 'order_type_id' => 2, 'dish_id' => 3],
            ['day' => 'Friday', 'order_type_id' => 2, 'dish_id' => 4],
            ['day' => 'Friday', 'order_type_id' => 2, 'dish_id' => 5],
            ['day' => 'Friday', 'order_type_id' => 2, 'dish_id' => 6],
            ['day' => 'Friday', 'order_type_id' => 2, 'dish_id' => 7],
            ['day' => 'Saturday', 'order_type_id' => 2, 'dish_id' => 1],
            ['day' => 'Saturday', 'order_type_id' => 2, 'dish_id' => 2],
            ['day' => 'Saturday', 'order_type_id' => 2, 'dish_id' => 3],
            ['day' => 'Saturday', 'order_type_id' => 2, 'dish_id' => 4],
            ['day' => 'Saturday', 'order_type_id' => 2, 'dish_id' => 5],
            ['day' => 'Saturday', 'order_type_id' => 2, 'dish_id' => 6],
            ['day' => 'Saturday', 'order_type_id' => 2, 'dish_id' => 14],
            ['day' => 'Saturday', 'order_type_id' => 2, 'dish_id' => 15],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 1],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 2],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 3],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 4],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 5],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 6],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 7],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 8],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 9],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 10],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 11],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 12],
            ['day' => 'Monday', 'order_type_id' => 3, 'dish_id' => 13],
            ['day' => 'Tuesday', 'order_type_id' => 3, 'dish_id' => 1],
            ['day' => 'Tuesday', 'order_type_id' => 3, 'dish_id' => 2],
            ['day' => 'Tuesday', 'order_type_id' => 3, 'dish_id' => 3],
            ['day' => 'Tuesday', 'order_type_id' => 3, 'dish_id' => 4],
            ['day' => 'Tuesday', 'order_type_id' => 3, 'dish_id' => 5],
            ['day' => 'Tuesday', 'order_type_id' => 3, 'dish_id' => 6],
            ['day' => 'Tuesday', 'order_type_id' => 3, 'dish_id' => 7],
            ['day' => 'Wednesday', 'order_type_id' => 3, 'dish_id' => 3],
            ['day' => 'Wednesday', 'order_type_id' => 3, 'dish_id' => 4],
            ['day' => 'Wednesday', 'order_type_id' => 3, 'dish_id' => 5],
            ['day' => 'Wednesday', 'order_type_id' => 3, 'dish_id' => 6],
            ['day' => 'Wednesday', 'order_type_id' => 3, 'dish_id' => 7],
            ['day' => 'Wednesday', 'order_type_id' => 3, 'dish_id' => 8],
            ['day' => 'Wednesday', 'order_type_id' => 3, 'dish_id' => 9],
            ['day' => 'Wednesday', 'order_type_id' => 3, 'dish_id' => 10],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 1],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 2],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 5],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 6],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 7],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 8],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 9],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 14],
            ['day' => 'Thursday', 'order_type_id' => 3, 'dish_id' => 15],
            ['day' => 'Friday', 'order_type_id' => 3, 'dish_id' => 1],
            ['day' => 'Friday', 'order_type_id' => 3, 'dish_id' => 2],
            ['day' => 'Friday', 'order_type_id' => 3, 'dish_id' => 3],
            ['day' => 'Friday', 'order_type_id' => 3, 'dish_id' => 4],
            ['day' => 'Friday', 'order_type_id' => 3, 'dish_id' => 5],
            ['day' => 'Friday', 'order_type_id' => 3, 'dish_id' => 6],
            ['day' => 'Friday', 'order_type_id' => 3, 'dish_id' => 7],
            ['day' => 'Saturday', 'order_type_id' => 3, 'dish_id' => 1],
            ['day' => 'Saturday', 'order_type_id' => 3, 'dish_id' => 2],
            ['day' => 'Saturday', 'order_type_id' => 3, 'dish_id' => 3],
            ['day' => 'Saturday', 'order_type_id' => 3, 'dish_id' => 4],
            ['day' => 'Saturday', 'order_type_id' => 3, 'dish_id' => 5],
            ['day' => 'Saturday', 'order_type_id' => 3, 'dish_id' => 6],
            ['day' => 'Saturday', 'order_type_id' => 3, 'dish_id' => 14],
            ['day' => 'Saturday', 'order_type_id' => 3, 'dish_id' => 15],
        ];
        foreach($data as $val){
            WeeklyDishList::create($val);
        }
    }
}
